insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Irvine Phipp', '27843 Village Green Plaza', '2023-02-22');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Trevar Josuweit', '001 Dennis Lane', '2022-12-26');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Atlanta Piddick', '33 Sachs Place', '2023-08-21');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Wolfie Sowerbutts', '46 Sugar Park', '2023-06-25');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Eldredge Sapson', '2 Bunker Hill Drive', '2023-03-17');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Jennica Vyel', '5548 Park Meadow Road', '2023-08-17');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Kirbee D''Hooge', '7937 Wayridge Plaza', '2023-05-03');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Dorian Dorricott', '9341 Johnson Point', '2023-08-22');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Erik Shilliday', '11 International Park', '2023-10-20');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Gussie Jenkinson', '8 Morning Terrace', '2023-10-27');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Rochette Firmager', '2484 Haas Trail', '2023-03-03');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Rossy Tuckwood', '1350 Walton Trail', '2023-10-21');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Arda Klemenz', '746 Kinsman Circle', '2023-06-19');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Rochella McMurty', '83 Dexter Street', '2023-05-17');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Maryjo Garralts', '254 Judy Center', '2023-11-01');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Mirabel Creser', '5 Eagan Avenue', '2023-01-29');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Glynnis Hankinson', '5 Truax Place', '2023-08-24');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Derward Beamand', '862 Westport Junction', '2023-04-01');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Rheta Tummond', '3 Quincy Pass', '2023-06-06');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Virgie Ashleigh', '52 Maple Wood Trail', '2023-09-21');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Eydie Feige', '279 Alpine Point', '2023-09-07');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Grier Hullock', '385 Cherokee Trail', '2023-03-18');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Dyna Beade', '5 Hollow Ridge Place', '2023-05-26');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Jenifer Bouzan', '70 Farragut Hill', '2023-02-25');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Timmie Willbourne', '0387 Anderson Alley', '2023-09-24');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Tanney Antonelli', '28529 Continental Point', '2022-11-24');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Sol Kobisch', '16114 Browning Road', '2023-04-17');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Elbertina Mallatratt', '31325 Canary Trail', '2023-10-29');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Alexandr Pardal', '214 8th Road', '2023-04-26');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Kenyon Allmann', '637 Nova Trail', '2023-05-28');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Brit Boissieux', '188 Morningstar Place', '2023-09-08');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Sephira Danford', '80 Bashford Drive', '2022-12-17');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Dorree Leipnik', '1 Fulton Parkway', '2023-04-17');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lodovico Evequot', '001 Lillian Court', '2023-10-30');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lynett Bogart', '59622 Vernon Point', '2023-01-23');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Hedy Bulfit', '3 Coolidge Pass', '2023-07-06');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Garrik Simpkins', '10 Becker Pass', '2023-04-13');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Stanislaus Coltart', '08734 Stone Corner Circle', '2023-02-13');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Kathe Blezard', '498 Talmadge Road', '2023-05-30');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Fan Malyj', '198 Eagan Trail', '2023-06-29');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Caesar Lightollers', '956 Ruskin Avenue', '2023-02-03');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Jorry Greener', '7781 Artisan Pass', '2022-12-27');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Maris Divell', '68 Emmet Circle', '2023-07-09');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Alex Di Francecshi', '285 Shasta Hill', '2023-03-05');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Shayna Dmitrichenko', '2346 Loftsgordon Road', '2023-08-19');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Giff Thackwray', '1547 Reindahl Alley', '2023-01-12');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Salvatore Andrzejowski', '2 Riverside Junction', '2023-11-04');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Atlante Landes', '6312 Parkside Pass', '2023-03-22');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Verene Marshland', '660 Milwaukee Way', '2023-09-16');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Peter Rudledge', '2 Sheridan Junction', '2023-06-28');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Sheryl Durant', '3 Red Cloud Lane', '2023-02-19');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Skye Pelz', '26341 Fuller Park', '2023-01-10');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Ebony Holtom', '78 Schiller Point', '2023-10-20');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Parker Vaan', '0153 Burrows Place', '2023-02-14');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Burgess Testin', '27 Michigan Park', '2023-01-03');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Bernardo Hirthe', '45 Sachtjen Alley', '2023-01-01');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Stafford Daymond', '9 Carberry Way', '2022-12-03');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Riobard Pickance', '8 Briar Crest Junction', '2023-01-13');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Cassie Pacheco', '06 Alpine Alley', '2023-08-13');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Blake Earingey', '70 Fulton Plaza', '2023-04-11');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Anabelle Seeman', '2 Bowman Pass', '2023-07-25');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Karoly Di Claudio', '244 Atwood Alley', '2023-02-02');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Homere Kobierzycki', '44 Montana Point', '2023-07-10');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Elisabetta Willowby', '9 Mcbride Plaza', '2023-09-14');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Nadean Morefield', '8 Kings Terrace', '2022-12-29');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Delano Marsy', '9 Fairfield Crossing', '2023-02-02');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Lisa Grunder', '4382 Rigney Place', '2023-06-12');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Augustina Sucre', '65 International Way', '2023-01-29');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Isabeau Penticoot', '2102 Washington Drive', '2023-08-04');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Waylan Emmott', '79484 Judy Street', '2022-12-24');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Raimondo Hardington', '07 Moland Crossing', '2023-04-18');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Dallis Midgely', '05208 Fairview Road', '2023-09-24');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Kalina Cleiment', '801 Coolidge Plaza', '2023-02-16');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Pamella Caspell', '64 Northwestern Junction', '2023-02-10');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Stearn Sor', '86048 Oneill Circle', '2022-12-21');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Sal Carden', '3 Meadow Ridge Alley', '2023-02-06');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Trixi McCaffery', '26218 Straubel Lane', '2023-10-09');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Godfry Shuard', '51 Scott Avenue', '2022-12-24');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Cobb Hourston', '354 Goodland Place', '2023-05-14');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Grove Eldritt', '210 Oak Valley Plaza', '2023-09-07');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Emelda Daintree', '792 Northview Hill', '2022-12-21');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Blanch Probets', '39281 Miller Court', '2023-07-09');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Violet Matyugin', '75294 Kedzie Junction', '2023-10-21');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Naomi Leason', '3641 Dovetail Park', '2023-09-20');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Dorolisa MacKimmie', '247 Buell Plaza', '2023-01-22');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Hall Leece', '930 Monterey Center', '2023-04-16');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Palmer Tesauro', '62508 Corscot Drive', '2023-06-13');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Fair Firbank', '680 Pawling Point', '2023-05-04');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Antoinette Ince', '628 Ridgeview Parkway', '2023-08-08');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Brenna Allingham', '229 Fulton Pass', '2023-08-23');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Kimbell Poure', '0620 Sutherland Circle', '2023-09-22');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Mathilde Scuse', '244 Mayfield Circle', '2022-12-17');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Gustavus Teasell', '7 Fulton Avenue', '2022-12-12');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Tripp Butterley', '818 Milwaukee Way', '2023-02-18');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Estell Rodolfi', '3831 Holmberg Junction', '2023-01-15');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Griswold Sidsaff', '6937 Killdeer Way', '2023-01-03');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Krissie Charlton', '940 Southridge Trail', '2023-01-07');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Jamie O''Bradane', '9 Mayfield Center', '2022-12-24');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Demetria Caldeiro', '7 Clarendon Court', '2023-05-04');
insert into pasajeros (nombre, direccion_residencia, fecha_nacimiento) values ('Iris Geldeford', '196 Village Hill', '2023-07-15');
