insert into trenes (modelo, capacidad) values ('Laser', 1);
insert into trenes (modelo, capacidad) values ('F150', 2);
insert into trenes (modelo, capacidad) values ('Golf', 3);
insert into trenes (modelo, capacidad) values ('Colt', 4);
insert into trenes (modelo, capacidad) values ('80', 5);
insert into trenes (modelo, capacidad) values ('Touareg', 6);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 7);
insert into trenes (modelo, capacidad) values ('Grand Cherokee', 8);
insert into trenes (modelo, capacidad) values ('Z8', 9);
insert into trenes (modelo, capacidad) values ('L-Series', 10);
insert into trenes (modelo, capacidad) values ('100', 11);
insert into trenes (modelo, capacidad) values ('Mariner', 12);
insert into trenes (modelo, capacidad) values ('Park Avenue', 13);
insert into trenes (modelo, capacidad) values ('GLI', 14);
insert into trenes (modelo, capacidad) values ('Loyale', 15);
insert into trenes (modelo, capacidad) values ('Cayenne', 16);
insert into trenes (modelo, capacidad) values ('Rio', 17);
insert into trenes (modelo, capacidad) values ('Avalanche', 18);
insert into trenes (modelo, capacidad) values ('Torino', 19);
insert into trenes (modelo, capacidad) values ('Ciera', 20);
insert into trenes (modelo, capacidad) values ('TT', 21);
insert into trenes (modelo, capacidad) values ('Avenger', 22);
insert into trenes (modelo, capacidad) values ('200SX', 23);
insert into trenes (modelo, capacidad) values ('Ram 1500 Club', 24);
insert into trenes (modelo, capacidad) values ('GTI', 25);
insert into trenes (modelo, capacidad) values ('Range Rover', 26);
insert into trenes (modelo, capacidad) values ('GT350', 27);
insert into trenes (modelo, capacidad) values ('Skyhawk', 28);
insert into trenes (modelo, capacidad) values ('Cayenne', 29);
insert into trenes (modelo, capacidad) values ('S60', 30);
insert into trenes (modelo, capacidad) values ('V8', 31);
insert into trenes (modelo, capacidad) values ('Truck', 32);
insert into trenes (modelo, capacidad) values ('626', 33);
insert into trenes (modelo, capacidad) values ('Cobalt', 34);
insert into trenes (modelo, capacidad) values ('Sprinter 3500', 35);
insert into trenes (modelo, capacidad) values ('Century', 36);
insert into trenes (modelo, capacidad) values ('Rogue', 37);
insert into trenes (modelo, capacidad) values ('Prius', 38);
insert into trenes (modelo, capacidad) values ('G', 39);
insert into trenes (modelo, capacidad) values ('Capri', 40);
insert into trenes (modelo, capacidad) values ('Grand Prix', 41);
insert into trenes (modelo, capacidad) values ('Golf', 42);
insert into trenes (modelo, capacidad) values ('Justy', 43);
insert into trenes (modelo, capacidad) values ('Elantra', 44);
insert into trenes (modelo, capacidad) values ('GX', 45);
insert into trenes (modelo, capacidad) values ('Esprit', 46);
insert into trenes (modelo, capacidad) values ('88', 47);
insert into trenes (modelo, capacidad) values ('S80', 48);
insert into trenes (modelo, capacidad) values ('Armada', 49);
insert into trenes (modelo, capacidad) values ('Explorer Sport Trac', 50);
insert into trenes (modelo, capacidad) values ('HHR', 51);
insert into trenes (modelo, capacidad) values ('5 Series', 52);
insert into trenes (modelo, capacidad) values ('Avalon', 53);
insert into trenes (modelo, capacidad) values ('Sierra 1500', 54);
insert into trenes (modelo, capacidad) values ('944', 55);
insert into trenes (modelo, capacidad) values ('Mazda5', 56);
insert into trenes (modelo, capacidad) values ('Z4 M', 57);
insert into trenes (modelo, capacidad) values ('Ram 2500', 58);
insert into trenes (modelo, capacidad) values ('Tracer', 59);
insert into trenes (modelo, capacidad) values ('Mustang', 60);
insert into trenes (modelo, capacidad) values ('4Runner', 61);
insert into trenes (modelo, capacidad) values ('Rio', 62);
insert into trenes (modelo, capacidad) values ('Ranger', 63);
insert into trenes (modelo, capacidad) values ('Integra', 64);
insert into trenes (modelo, capacidad) values ('Odyssey', 65);
insert into trenes (modelo, capacidad) values ('FJ Cruiser', 66);
insert into trenes (modelo, capacidad) values ('Verona', 67);
insert into trenes (modelo, capacidad) values ('Eurovan', 68);
insert into trenes (modelo, capacidad) values ('Land Cruiser', 69);
insert into trenes (modelo, capacidad) values ('626', 70);
insert into trenes (modelo, capacidad) values ('QX', 71);
insert into trenes (modelo, capacidad) values ('Astro', 72);
insert into trenes (modelo, capacidad) values ('M3', 73);
insert into trenes (modelo, capacidad) values ('Grand Prix', 74);
insert into trenes (modelo, capacidad) values ('944', 75);
insert into trenes (modelo, capacidad) values ('300E', 76);
insert into trenes (modelo, capacidad) values ('Outlander', 77);
insert into trenes (modelo, capacidad) values ('Regal', 78);
insert into trenes (modelo, capacidad) values ('911', 79);
insert into trenes (modelo, capacidad) values ('Ram 2500', 80);
insert into trenes (modelo, capacidad) values ('Colt', 81);
insert into trenes (modelo, capacidad) values ('Tempest', 82);
insert into trenes (modelo, capacidad) values ('Legacy', 83);
insert into trenes (modelo, capacidad) values ('Outback', 84);
insert into trenes (modelo, capacidad) values ('330', 85);
insert into trenes (modelo, capacidad) values ('Z4', 86);
insert into trenes (modelo, capacidad) values ('Taurus', 87);
insert into trenes (modelo, capacidad) values ('B-Series', 88);
insert into trenes (modelo, capacidad) values ('G37', 89);
insert into trenes (modelo, capacidad) values ('F350', 90);
insert into trenes (modelo, capacidad) values ('2500 Club Coupe', 91);
insert into trenes (modelo, capacidad) values ('Dakota', 92);
insert into trenes (modelo, capacidad) values ('Transit Connect', 93);
insert into trenes (modelo, capacidad) values ('1500', 94);
insert into trenes (modelo, capacidad) values ('Reno', 95);
insert into trenes (modelo, capacidad) values ('Avanti', 96);
insert into trenes (modelo, capacidad) values ('Montero', 97);
insert into trenes (modelo, capacidad) values ('XC90', 98);
insert into trenes (modelo, capacidad) values ('Xterra', 99);
insert into trenes (modelo, capacidad) values ('LS', 100);
